### PR TITLE
Add '/api/v1/files/get' endpoint to download files and add download button to web UI

### PR DESCRIPTION
**Pull request by ptcNOP**
By default, files are downloaded as password protected zipfiles (pw: infected).
Raw files can be requested using '?raw=true'.

### CODE REVIEW

**Comment by ptcNOP** [comment]
screen shot 2017-09-01 at 14 20 03

**Comment by awest1339** [comment]
@ptcNOP @clenk would the download dropdown button look better on the right side?

**Comment by clenk** [comment]
Yes, I think it should replace/be in the same spot as the old "Download JSON" button.

**Comment by ptcNOP** [comment]
Yeah, definitely. I spent some time trying to get that to work and didn't have much luck. I was hoping with better CSS skills might be able to do it pretty quick.

**Comment by clenk** [comment]
I think you have to add an id to `<div class="dropdown">` and then set css for it like was on the previous button:

```css
#dl-json {
    position: absolute;
    padding-left: 25px;
    padding-right: 25px;
    right: 5px;
}
@media (min-width: 992px) {
    #dl-json {
        right: 16.66666667%;
    }
}
```

(replace `dl-json` with the id you give that div - `dl-json` isn't needed so you could just replace it in the css)
(but I haven't tried this out myself)

**Comment by ptcNOP** [comment]
Hmm...I did something like this for the button, and it ended up overlapping with the tags input box. I'm pretty sure I wasn't id-ing the div.

**Comment by ptcNOP** [comment]
Well...it doesn't seem like all browsers respect that. Looks good on safari and firefox, but chrome seems to be ignoring it.

**Comment by clenk** [comment]
Seems to work for me in Firefox and Chrome.

**Comment by awest1339** [comment]
@ptcNOP can we add the default password for unzipping the downloaded sample somewhere? Maybe to the help popup in the web UI?

**Comment by clenk** [comment]
Don't think this was meant to be closed yet... (last 2 commits look like they still need to be merged)

**Comment by ptcNOP** [comment]
Yeah, I'm kinda confused what happened here.

**Comment by clenk** [comment]
Drew's commit "Fix #21" was from a while ago, and it was referring to issue #21 on the /mitre/multiscanner repo

**Comment by awest1339** [comment]
Re-merged. This should be fixed now. 👍

**Pull request closed without merging**
