### PR TITLE
Add ssdeep comparison analytic

### PR DESCRIPTION
**Pull request by ptcNOP**
Designed to be run on a regular basis (e.g., nightly). For each sample that has not run ssdeep analytic, search for samples where ssdeep.compare > 0 based on chunksize, chunk 7grams, and double-chunk 7grams. Update sample with any matches and mark ssdeep analytic as having run.

Changes:
- Updates elasticsearch template to support optimizations
- Adds new analytics directory for future analytics

### CODE REVIEW

**Comment by awest1339** [comment]
@Drewsif thoughts?

**Comment by Drewsif** [comment]
It looks really solid to me. We should add something to the modules.md file to say "hey btw you should run this nightly!"

**Comment by awest1339** [comment]
@ptcNOP can we refactor this to use the Python ElasticSearch client library (https://elasticsearch-py.readthedocs.io/en/master/) instead of the Python ElasticSearch DSL client library (https://elasticsearch-dsl.readthedocs.io/en/latest/). 
Project preference, plus I think the lower level client is a little more powerful, customizable, and performant.

**Comment by awest1339** [comment]
@ptcNOP can we add usage docs to the top level doc strings?

**Pull request merged**
